# Generated by Django 2.1.4 on 2018-12-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_changed_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set the reference partial name', max_length=200)),
                ('title', models.CharField(blank=True, help_text='The title to display in the partial', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='The subtitle to display in the partial', max_length=200)),
                ('text', models.TextField(blank=True, help_text='The text body to display in the partial')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='PartialsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set the reference group name', max_length=200)),
                ('slug', models.SlugField(help_text='Set a query-friendly label (auto-generated from name)')),
            ],
            options={
                'verbose_name': 'partials group',
                'verbose_name_plural': 'partials groups',
            },
        ),
        migrations.RenameField(
            model_name='page',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False, help_text='Set page as home page without ambiguity', verbose_name='Is Homepage'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AddField(
            model_name='partial',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Arrange partials into groups', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.PartialsGroup'),
        ),
        migrations.AddField(
            model_name='page',
            name='partials',
            field=models.ManyToManyField(blank=True, help_text='Add page partials', to='pages.Partial'),
        ),
    ]
