# Generated by Django 2.1.4 on 2018-12-20 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_added_partial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='partials',
        ),
        migrations.AddField(
            model_name='partial',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Set the page where to display this partial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Page'),
        ),
    ]
